# Copyright (C) 2024 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/elitelte_kor/setup-makefiles.sh


# Vendor libs
PRODUCT_COPY_FILES += \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/lib-ims-rcscmjni.so:system/vendor/lib/lib-ims-rcscmjni.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/lib-imsrcs.so:system/vendor/lib/lib-imsrcs.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/lib-imsrcscm.so:system/vendor/lib/lib-imsrcscm.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/lib-imsrcscmclient.so:system/vendor/lib/lib-imsrcscmclient.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/lib-imsrcscmservice.so:system/vendor/lib/lib-imsrcscmservice.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/lib-imss.so:system/vendor/lib/lib-imss.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/lib-imsvt.so:system/vendor/lib/lib-imsvt.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/lib-imsxml.so:system/vendor/lib/lib-imsxml.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/lib-rcsimssjni.so:system/vendor/lib/lib-rcsimssjni.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/lib-rcsjni.so:system/vendor/lib/lib-rcsjni.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/lib-sec-disp.so:system/vendor/lib/lib-sec-disp.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libAlacSwDec.so:system/vendor/lib/libAlacSwDec.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libApeSwDec.so:system/vendor/lib/libApeSwDec.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libChamomilePA.so:system/vendor/lib/libChamomilePA.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libCommandSvc.so:system/vendor/lib/libCommandSvc.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libExtendedExtractor.so:system/vendor/lib/libExtendedExtractor.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libFIDOKeyProvisioning.so:system/vendor/lib/libFIDOKeyProvisioning.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libFidoCrypto.so:system/vendor/lib/libFidoCrypto.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libFidoCryptoJNI.so:system/vendor/lib/libFidoCryptoJNI.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libFidoSuiJNI.so:system/vendor/lib/libFidoSuiJNI.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libFileMux.so:system/vendor/lib/libFileMux.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libFlacSwDec.so:system/vendor/lib/libFlacSwDec.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libGPTEE.so:system/vendor/lib/libGPTEE.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libGPreqcancel.so:system/vendor/lib/libGPreqcancel.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libGPreqcancel_svc.so:system/vendor/lib/libGPreqcancel_svc.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libMpeg4SwEncoder.so:system/vendor/lib/libMpeg4SwEncoder.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libOmxAlacDec.so:system/vendor/lib/libOmxAlacDec.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libOmxAlacDecSw.so:system/vendor/lib/libOmxAlacDecSw.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libOmxAmrwbplusDec.so:system/vendor/lib/libOmxAmrwbplusDec.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libOmxApeDec.so:system/vendor/lib/libOmxApeDec.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libOmxApeDecSw.so:system/vendor/lib/libOmxApeDecSw.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libOmxVideoDSMode.so:system/vendor/lib/libOmxVideoDSMode.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libOmxWmaDec.so:system/vendor/lib/libOmxWmaDec.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libSampleAuthJNI.so:system/vendor/lib/libSampleAuthJNI.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libSecureSampleAuthJNI.so:system/vendor/lib/libSecureSampleAuthJNI.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libSecureUILib.so:system/vendor/lib/libSecureUILib.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libStDrvInt.so:system/vendor/lib/libStDrvInt.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libSubSystemShutdown.so:system/vendor/lib/libSubSystemShutdown.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libacdb-fts.so:system/vendor/lib/libacdb-fts.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libacdbmapper.so:system/vendor/lib/libacdbmapper.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libactuator_ad5816g.so:system/vendor/lib/libactuator_ad5816g.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libactuator_ad5823.so:system/vendor/lib/libactuator_ad5823.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libactuator_ak7345.so:system/vendor/lib/libactuator_ak7345.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libactuator_ak7371.so:system/vendor/lib/libactuator_ak7371.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libactuator_ak7372.so:system/vendor/lib/libactuator_ak7372.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libactuator_bu64244gwz.so:system/vendor/lib/libactuator_bu64244gwz.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libactuator_bu64297.so:system/vendor/lib/libactuator_bu64297.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libactuator_dw9714.so:system/vendor/lib/libactuator_dw9714.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libactuator_dw9716.so:system/vendor/lib/libactuator_dw9716.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libactuator_dw9761b.so:system/vendor/lib/libactuator_dw9761b.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libactuator_dw9806.so:system/vendor/lib/libactuator_dw9806.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libactuator_dw9806b.so:system/vendor/lib/libactuator_dw9806b.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libactuator_dw9807.so:system/vendor/lib/libactuator_dw9807.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libactuator_lc898122.so:system/vendor/lib/libactuator_lc898122.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libactuator_lc898212xd.so:system/vendor/lib/libactuator_lc898212xd.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libactuator_rohm_bu64243gwz.so:system/vendor/lib/libactuator_rohm_bu64243gwz.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libactuator_zc535.so:system/vendor/lib/libactuator_zc535.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libadm.so:system/vendor/lib/libadm.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libadpcmdec.so:system/vendor/lib/libadpcmdec.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libadsp_default_listener.so:system/vendor/lib/libadsp_default_listener.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libalarmservice_jni.so:system/vendor/lib/libalarmservice_jni.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libasn1cper.so:system/vendor/lib/libasn1cper.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libasn1crt.so:system/vendor/lib/libasn1crt.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libasn1crtx.so:system/vendor/lib/libasn1crtx.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libaudioalsa.so:system/vendor/lib/libaudioalsa.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libaudioparsers.so:system/vendor/lib/libaudioparsers.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libavenhancements.so:system/vendor/lib/libavenhancements.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libbccQTI.so:system/vendor/lib/libbccQTI.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libbtnv.so:system/vendor/lib/libbtnv.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libc2d30-a5xx.so:system/vendor/lib/libc2d30-a5xx.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libc2d30_bltlib.so:system/vendor/lib/libc2d30_bltlib.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromaflash.so:system/vendor/lib/libchromaflash.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_imx241_3a_4k_preview.so:system/vendor/lib/libchromatix_imx241_3a_4k_preview.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_imx241_3a_4k_video.so:system/vendor/lib/libchromatix_imx241_3a_4k_video.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_imx241_3a_hfr_120.so:system/vendor/lib/libchromatix_imx241_3a_hfr_120.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_imx241_3a_night_preview.so:system/vendor/lib/libchromatix_imx241_3a_night_preview.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_imx241_3a_panorama_preview.so:system/vendor/lib/libchromatix_imx241_3a_panorama_preview.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_imx241_3a_sports_preview.so:system/vendor/lib/libchromatix_imx241_3a_sports_preview.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_imx241_3a_zsl_preview.so:system/vendor/lib/libchromatix_imx241_3a_zsl_preview.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_imx241_3a_zsl_video.so:system/vendor/lib/libchromatix_imx241_3a_zsl_video.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_imx241_common.so:system/vendor/lib/libchromatix_imx241_common.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_imx241_cpp_hfr_120.so:system/vendor/lib/libchromatix_imx241_cpp_hfr_120.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_imx241_cpp_iso_snapshot.so:system/vendor/lib/libchromatix_imx241_cpp_iso_snapshot.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_imx241_cpp_liveshot.so:system/vendor/lib/libchromatix_imx241_cpp_liveshot.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_imx241_cpp_night_snapshot.so:system/vendor/lib/libchromatix_imx241_cpp_night_snapshot.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_imx241_cpp_panorama_snapshot.so:system/vendor/lib/libchromatix_imx241_cpp_panorama_snapshot.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_imx241_cpp_preview.so:system/vendor/lib/libchromatix_imx241_cpp_preview.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_imx241_cpp_snapshot.so:system/vendor/lib/libchromatix_imx241_cpp_snapshot.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_imx241_cpp_sports_snapshot.so:system/vendor/lib/libchromatix_imx241_cpp_sports_snapshot.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_imx241_cpp_video.so:system/vendor/lib/libchromatix_imx241_cpp_video.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_imx241_cpp_video_4k.so:system/vendor/lib/libchromatix_imx241_cpp_video_4k.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_imx241_isp_default_video.so:system/vendor/lib/libchromatix_imx241_isp_default_video.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_imx241_isp_hfr_120.so:system/vendor/lib/libchromatix_imx241_isp_hfr_120.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_imx241_isp_mode_iso.so:system/vendor/lib/libchromatix_imx241_isp_mode_iso.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_imx241_isp_mode_night.so:system/vendor/lib/libchromatix_imx241_isp_mode_night.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_imx241_isp_mode_panorama.so:system/vendor/lib/libchromatix_imx241_isp_mode_panorama.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_imx241_isp_mode_sports.so:system/vendor/lib/libchromatix_imx241_isp_mode_sports.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_imx241_isp_snapshot.so:system/vendor/lib/libchromatix_imx241_isp_snapshot.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_imx241_postproc.so:system/vendor/lib/libchromatix_imx241_postproc.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_m16ql_3a_4k_preview.so:system/vendor/lib/libchromatix_s5k3p8sx_m16ql_3a_4k_preview.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_m16ql_3a_4k_video.so:system/vendor/lib/libchromatix_s5k3p8sx_m16ql_3a_4k_video.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_m16ql_3a_hfr_120.so:system/vendor/lib/libchromatix_s5k3p8sx_m16ql_3a_hfr_120.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_m16ql_3a_night_preview.so:system/vendor/lib/libchromatix_s5k3p8sx_m16ql_3a_night_preview.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_m16ql_3a_panorama_preview.so:system/vendor/lib/libchromatix_s5k3p8sx_m16ql_3a_panorama_preview.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_m16ql_3a_sports_preview.so:system/vendor/lib/libchromatix_s5k3p8sx_m16ql_3a_sports_preview.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_m16ql_3a_wechat_preview.so:system/vendor/lib/libchromatix_s5k3p8sx_m16ql_3a_wechat_preview.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_m16ql_3a_wechat_video.so:system/vendor/lib/libchromatix_s5k3p8sx_m16ql_3a_wechat_video.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_m16ql_3a_zsl_preview.so:system/vendor/lib/libchromatix_s5k3p8sx_m16ql_3a_zsl_preview.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_m16ql_3a_zsl_video.so:system/vendor/lib/libchromatix_s5k3p8sx_m16ql_3a_zsl_video.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_m16ql_common.so:system/vendor/lib/libchromatix_s5k3p8sx_m16ql_common.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_m16ql_cpp_hfr_120.so:system/vendor/lib/libchromatix_s5k3p8sx_m16ql_cpp_hfr_120.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_m16ql_cpp_iso_snapshot.so:system/vendor/lib/libchromatix_s5k3p8sx_m16ql_cpp_iso_snapshot.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_m16ql_cpp_liveshot.so:system/vendor/lib/libchromatix_s5k3p8sx_m16ql_cpp_liveshot.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_m16ql_cpp_lls_snapshot.so:system/vendor/lib/libchromatix_s5k3p8sx_m16ql_cpp_lls_snapshot.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_m16ql_cpp_night_snapshot.so:system/vendor/lib/libchromatix_s5k3p8sx_m16ql_cpp_night_snapshot.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_m16ql_cpp_panorama_snapshot.so:system/vendor/lib/libchromatix_s5k3p8sx_m16ql_cpp_panorama_snapshot.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_m16ql_cpp_preview.so:system/vendor/lib/libchromatix_s5k3p8sx_m16ql_cpp_preview.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_m16ql_cpp_snapshot.so:system/vendor/lib/libchromatix_s5k3p8sx_m16ql_cpp_snapshot.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_m16ql_cpp_sports_snapshot.so:system/vendor/lib/libchromatix_s5k3p8sx_m16ql_cpp_sports_snapshot.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_m16ql_cpp_sr_snapshot.so:system/vendor/lib/libchromatix_s5k3p8sx_m16ql_cpp_sr_snapshot.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_m16ql_cpp_video.so:system/vendor/lib/libchromatix_s5k3p8sx_m16ql_cpp_video.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_m16ql_cpp_video_4k.so:system/vendor/lib/libchromatix_s5k3p8sx_m16ql_cpp_video_4k.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_m16ql_cpp_video_wechat.so:system/vendor/lib/libchromatix_s5k3p8sx_m16ql_cpp_video_wechat.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_m16ql_isp_default_video.so:system/vendor/lib/libchromatix_s5k3p8sx_m16ql_isp_default_video.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_m16ql_isp_hfr_120.so:system/vendor/lib/libchromatix_s5k3p8sx_m16ql_isp_hfr_120.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_m16ql_isp_mode_iso.so:system/vendor/lib/libchromatix_s5k3p8sx_m16ql_isp_mode_iso.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_m16ql_isp_mode_night.so:system/vendor/lib/libchromatix_s5k3p8sx_m16ql_isp_mode_night.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_m16ql_isp_mode_panorama.so:system/vendor/lib/libchromatix_s5k3p8sx_m16ql_isp_mode_panorama.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_m16ql_isp_mode_sports.so:system/vendor/lib/libchromatix_s5k3p8sx_m16ql_isp_mode_sports.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_m16ql_isp_mode_sr.so:system/vendor/lib/libchromatix_s5k3p8sx_m16ql_isp_mode_sr.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_m16ql_isp_mode_wechat.so:system/vendor/lib/libchromatix_s5k3p8sx_m16ql_isp_mode_wechat.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_m16ql_isp_snapshot.so:system/vendor/lib/libchromatix_s5k3p8sx_m16ql_isp_snapshot.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_m16ql_postproc.so:system/vendor/lib/libchromatix_s5k3p8sx_m16ql_postproc.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_m16ql_postproc_lds.so:system/vendor/lib/libchromatix_s5k3p8sx_m16ql_postproc_lds.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_m16ql_postproc_mode_sr.so:system/vendor/lib/libchromatix_s5k3p8sx_m16ql_postproc_mode_sr.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_o16ql_common.so:system/vendor/lib/libchromatix_s5k3p8sx_o16ql_common.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_o16ql_cpp_hfr_120.so:system/vendor/lib/libchromatix_s5k3p8sx_o16ql_cpp_hfr_120.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_o16ql_cpp_liveshot.so:system/vendor/lib/libchromatix_s5k3p8sx_o16ql_cpp_liveshot.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_o16ql_cpp_preview_high.so:system/vendor/lib/libchromatix_s5k3p8sx_o16ql_cpp_preview_high.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_o16ql_cpp_preview_low.so:system/vendor/lib/libchromatix_s5k3p8sx_o16ql_cpp_preview_low.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_o16ql_cpp_snapshot_high.so:system/vendor/lib/libchromatix_s5k3p8sx_o16ql_cpp_snapshot_high.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_o16ql_cpp_snapshot_lls_high.so:system/vendor/lib/libchromatix_s5k3p8sx_o16ql_cpp_snapshot_lls_high.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_o16ql_cpp_snapshot_low.so:system/vendor/lib/libchromatix_s5k3p8sx_o16ql_cpp_snapshot_low.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_o16ql_cpp_video_high.so:system/vendor/lib/libchromatix_s5k3p8sx_o16ql_cpp_video_high.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_o16ql_cpp_video_low.so:system/vendor/lib/libchromatix_s5k3p8sx_o16ql_cpp_video_low.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_o16ql_cpp_vt_high.so:system/vendor/lib/libchromatix_s5k3p8sx_o16ql_cpp_vt_high.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_o16ql_cpp_vt_low.so:system/vendor/lib/libchromatix_s5k3p8sx_o16ql_cpp_vt_low.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_o16ql_default_video_lc898122.so:system/vendor/lib/libchromatix_s5k3p8sx_o16ql_default_video_lc898122.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_o16ql_hfr_120.so:system/vendor/lib/libchromatix_s5k3p8sx_o16ql_hfr_120.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_o16ql_hfr_120_lc898122.so:system/vendor/lib/libchromatix_s5k3p8sx_o16ql_hfr_120_lc898122.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_o16ql_liveshot.so:system/vendor/lib/libchromatix_s5k3p8sx_o16ql_liveshot.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_o16ql_postproc.so:system/vendor/lib/libchromatix_s5k3p8sx_o16ql_postproc.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_o16ql_preview_high.so:system/vendor/lib/libchromatix_s5k3p8sx_o16ql_preview_high.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_o16ql_preview_low.so:system/vendor/lib/libchromatix_s5k3p8sx_o16ql_preview_low.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_o16ql_snapshot_high.so:system/vendor/lib/libchromatix_s5k3p8sx_o16ql_snapshot_high.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_o16ql_snapshot_low.so:system/vendor/lib/libchromatix_s5k3p8sx_o16ql_snapshot_low.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_o16ql_video_high.so:system/vendor/lib/libchromatix_s5k3p8sx_o16ql_video_high.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_o16ql_video_low.so:system/vendor/lib/libchromatix_s5k3p8sx_o16ql_video_low.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_o16ql_vt_15fps_lc898122.so:system/vendor/lib/libchromatix_s5k3p8sx_o16ql_vt_15fps_lc898122.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_o16ql_vt_30fps_lc898122.so:system/vendor/lib/libchromatix_s5k3p8sx_o16ql_vt_30fps_lc898122.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_o16ql_vt_7fps_lc898122.so:system/vendor/lib/libchromatix_s5k3p8sx_o16ql_vt_7fps_lc898122.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_o16ql_vt_high.so:system/vendor/lib/libchromatix_s5k3p8sx_o16ql_vt_high.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_o16ql_vt_low.so:system/vendor/lib/libchromatix_s5k3p8sx_o16ql_vt_low.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k3p8sx_o16ql_zsl_preview_lc898122.so:system/vendor/lib/libchromatix_s5k3p8sx_o16ql_zsl_preview_lc898122.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k5e3yx_common.so:system/vendor/lib/libchromatix_s5k5e3yx_common.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k5e3yx_cpp_hfr_120.so:system/vendor/lib/libchromatix_s5k5e3yx_cpp_hfr_120.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k5e3yx_cpp_liveshot.so:system/vendor/lib/libchromatix_s5k5e3yx_cpp_liveshot.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k5e3yx_cpp_preview.so:system/vendor/lib/libchromatix_s5k5e3yx_cpp_preview.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k5e3yx_cpp_snapshot.so:system/vendor/lib/libchromatix_s5k5e3yx_cpp_snapshot.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k5e3yx_cpp_video.so:system/vendor/lib/libchromatix_s5k5e3yx_cpp_video.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k5e3yx_cpp_vt.so:system/vendor/lib/libchromatix_s5k5e3yx_cpp_vt.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k5e3yx_cpp_vt_15fps.so:system/vendor/lib/libchromatix_s5k5e3yx_cpp_vt_15fps.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k5e3yx_cpp_vt_30fps.so:system/vendor/lib/libchromatix_s5k5e3yx_cpp_vt_30fps.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k5e3yx_default_video_lc898122.so:system/vendor/lib/libchromatix_s5k5e3yx_default_video_lc898122.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k5e3yx_hfr_120.so:system/vendor/lib/libchromatix_s5k5e3yx_hfr_120.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k5e3yx_hfr_120_lc898122.so:system/vendor/lib/libchromatix_s5k5e3yx_hfr_120_lc898122.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k5e3yx_postproc.so:system/vendor/lib/libchromatix_s5k5e3yx_postproc.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k5e3yx_preview.so:system/vendor/lib/libchromatix_s5k5e3yx_preview.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k5e3yx_snapshot.so:system/vendor/lib/libchromatix_s5k5e3yx_snapshot.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k5e3yx_video.so:system/vendor/lib/libchromatix_s5k5e3yx_video.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k5e3yx_vt.so:system/vendor/lib/libchromatix_s5k5e3yx_vt.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k5e3yx_vt_15fps.so:system/vendor/lib/libchromatix_s5k5e3yx_vt_15fps.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k5e3yx_vt_15fps_lc898122.so:system/vendor/lib/libchromatix_s5k5e3yx_vt_15fps_lc898122.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k5e3yx_vt_30fps.so:system/vendor/lib/libchromatix_s5k5e3yx_vt_30fps.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k5e3yx_vt_30fps_lc898122.so:system/vendor/lib/libchromatix_s5k5e3yx_vt_30fps_lc898122.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k5e3yx_vt_lc898122.so:system/vendor/lib/libchromatix_s5k5e3yx_vt_lc898122.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_s5k5e3yx_zsl_preview_lc898122.so:system/vendor/lib/libchromatix_s5k5e3yx_zsl_preview_lc898122.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_1080p_preview_lc898122.so:system/vendor/lib/libchromatix_sr259_1080p_preview_lc898122.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_1080p_video_lc898122.so:system/vendor/lib/libchromatix_sr259_1080p_video_lc898122.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_4k_preview_lc898122.so:system/vendor/lib/libchromatix_sr259_4k_preview_lc898122.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_4k_video_lc898122.so:system/vendor/lib/libchromatix_sr259_4k_video_lc898122.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_common.so:system/vendor/lib/libchromatix_sr259_common.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_cpp_hfr_120.so:system/vendor/lib/libchromatix_sr259_cpp_hfr_120.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_cpp_hfr_60.so:system/vendor/lib/libchromatix_sr259_cpp_hfr_60.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_cpp_hfr_90.so:system/vendor/lib/libchromatix_sr259_cpp_hfr_90.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_cpp_liveshot.so:system/vendor/lib/libchromatix_sr259_cpp_liveshot.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_cpp_night.so:system/vendor/lib/libchromatix_sr259_cpp_night.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_cpp_preview.so:system/vendor/lib/libchromatix_sr259_cpp_preview.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_cpp_snapshot.so:system/vendor/lib/libchromatix_sr259_cpp_snapshot.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_cpp_video.so:system/vendor/lib/libchromatix_sr259_cpp_video.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_cpp_video_4k.so:system/vendor/lib/libchromatix_sr259_cpp_video_4k.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_cpp_vt.so:system/vendor/lib/libchromatix_sr259_cpp_vt.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_cpp_vt_30fps.so:system/vendor/lib/libchromatix_sr259_cpp_vt_30fps.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_cpp_vt_hd.so:system/vendor/lib/libchromatix_sr259_cpp_vt_hd.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_default_preview_lc898122.so:system/vendor/lib/libchromatix_sr259_default_preview_lc898122.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_default_video.so:system/vendor/lib/libchromatix_sr259_default_video.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_default_video_lc898122.so:system/vendor/lib/libchromatix_sr259_default_video_lc898122.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_hfr_120.so:system/vendor/lib/libchromatix_sr259_hfr_120.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_hfr_120_lc898122.so:system/vendor/lib/libchromatix_sr259_hfr_120_lc898122.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_hfr_60.so:system/vendor/lib/libchromatix_sr259_hfr_60.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_hfr_60_lc898122.so:system/vendor/lib/libchromatix_sr259_hfr_60_lc898122.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_hfr_90.so:system/vendor/lib/libchromatix_sr259_hfr_90.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_hfr_90_lc898122.so:system/vendor/lib/libchromatix_sr259_hfr_90_lc898122.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_liveshot.so:system/vendor/lib/libchromatix_sr259_liveshot.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_night_preview_lc898122.so:system/vendor/lib/libchromatix_sr259_night_preview_lc898122.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_postproc.so:system/vendor/lib/libchromatix_sr259_postproc.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_preview.so:system/vendor/lib/libchromatix_sr259_preview.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_snapshot.so:system/vendor/lib/libchromatix_sr259_snapshot.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_video_4k.so:system/vendor/lib/libchromatix_sr259_video_4k.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_vt.so:system/vendor/lib/libchromatix_sr259_vt.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_vt_30fps.so:system/vendor/lib/libchromatix_sr259_vt_30fps.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_vt_30fps_lc898122.so:system/vendor/lib/libchromatix_sr259_vt_30fps_lc898122.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_vt_hd.so:system/vendor/lib/libchromatix_sr259_vt_hd.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_vt_hd_lc898122.so:system/vendor/lib/libchromatix_sr259_vt_hd_lc898122.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_vt_lc898122.so:system/vendor/lib/libchromatix_sr259_vt_lc898122.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_zsl_preview_lc898122.so:system/vendor/lib/libchromatix_sr259_zsl_preview_lc898122.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr259_zsl_video_lc898122.so:system/vendor/lib/libchromatix_sr259_zsl_video_lc898122.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_3a_4k_preview.so:system/vendor/lib/libchromatix_sr846_y08qf_3a_4k_preview.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_3a_4k_video.so:system/vendor/lib/libchromatix_sr846_y08qf_3a_4k_video.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_3a_hfr_120.so:system/vendor/lib/libchromatix_sr846_y08qf_3a_hfr_120.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_3a_night_preview.so:system/vendor/lib/libchromatix_sr846_y08qf_3a_night_preview.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_3a_panorama_preview.so:system/vendor/lib/libchromatix_sr846_y08qf_3a_panorama_preview.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_3a_sports_preview.so:system/vendor/lib/libchromatix_sr846_y08qf_3a_sports_preview.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_3a_vt_24fps.so:system/vendor/lib/libchromatix_sr846_y08qf_3a_vt_24fps.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_3a_vt_30fps.so:system/vendor/lib/libchromatix_sr846_y08qf_3a_vt_30fps.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_3a_wechat_preview.so:system/vendor/lib/libchromatix_sr846_y08qf_3a_wechat_preview.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_3a_wechat_video.so:system/vendor/lib/libchromatix_sr846_y08qf_3a_wechat_video.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_3a_zsl_preview.so:system/vendor/lib/libchromatix_sr846_y08qf_3a_zsl_preview.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_3a_zsl_video.so:system/vendor/lib/libchromatix_sr846_y08qf_3a_zsl_video.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_common.so:system/vendor/lib/libchromatix_sr846_y08qf_common.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_cpp_hfr_120.so:system/vendor/lib/libchromatix_sr846_y08qf_cpp_hfr_120.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_cpp_iso_snapshot.so:system/vendor/lib/libchromatix_sr846_y08qf_cpp_iso_snapshot.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_cpp_liveshot.so:system/vendor/lib/libchromatix_sr846_y08qf_cpp_liveshot.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_cpp_lls_snapshot.so:system/vendor/lib/libchromatix_sr846_y08qf_cpp_lls_snapshot.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_cpp_night_snapshot.so:system/vendor/lib/libchromatix_sr846_y08qf_cpp_night_snapshot.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_cpp_panorama_snapshot.so:system/vendor/lib/libchromatix_sr846_y08qf_cpp_panorama_snapshot.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_cpp_preview.so:system/vendor/lib/libchromatix_sr846_y08qf_cpp_preview.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_cpp_snapshot.so:system/vendor/lib/libchromatix_sr846_y08qf_cpp_snapshot.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_cpp_sports_snapshot.so:system/vendor/lib/libchromatix_sr846_y08qf_cpp_sports_snapshot.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_cpp_sr_snapshot.so:system/vendor/lib/libchromatix_sr846_y08qf_cpp_sr_snapshot.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_cpp_video.so:system/vendor/lib/libchromatix_sr846_y08qf_cpp_video.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_cpp_video_4k.so:system/vendor/lib/libchromatix_sr846_y08qf_cpp_video_4k.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_cpp_video_wechat.so:system/vendor/lib/libchromatix_sr846_y08qf_cpp_video_wechat.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_isp_default_video.so:system/vendor/lib/libchromatix_sr846_y08qf_isp_default_video.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_isp_hfr_120.so:system/vendor/lib/libchromatix_sr846_y08qf_isp_hfr_120.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_isp_mode_iso.so:system/vendor/lib/libchromatix_sr846_y08qf_isp_mode_iso.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_isp_mode_night.so:system/vendor/lib/libchromatix_sr846_y08qf_isp_mode_night.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_isp_mode_panorama.so:system/vendor/lib/libchromatix_sr846_y08qf_isp_mode_panorama.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_isp_mode_sports.so:system/vendor/lib/libchromatix_sr846_y08qf_isp_mode_sports.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_isp_mode_sr.so:system/vendor/lib/libchromatix_sr846_y08qf_isp_mode_sr.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_isp_mode_wechat.so:system/vendor/lib/libchromatix_sr846_y08qf_isp_mode_wechat.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_isp_snapshot.so:system/vendor/lib/libchromatix_sr846_y08qf_isp_snapshot.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_postproc.so:system/vendor/lib/libchromatix_sr846_y08qf_postproc.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_postproc_lds.so:system/vendor/lib/libchromatix_sr846_y08qf_postproc_lds.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libchromatix_sr846_y08qf_postproc_mode_sr.so:system/vendor/lib/libchromatix_sr846_y08qf_postproc_mode_sr.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libcppf.so:system/vendor/lib/libcppf.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libdataitems.so:system/vendor/lib/libdataitems.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libdisp-aba.so:system/vendor/lib/libdisp-aba.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libdme_main.so:system/vendor/lib/libdme_main.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libdrc.so:system/vendor/lib/libdrc.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libfastcvadsp_stub.so:system/vendor/lib/libfastcvadsp_stub.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libflash_pmic.so:system/vendor/lib/libflash_pmic.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libflp.so:system/vendor/lib/libflp.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libgdtap.so:system/vendor/lib/libgdtap.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libizat_client_api.so:system/vendor/lib/libizat_client_api.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libjpegdmahw.so:system/vendor/lib/libjpegdmahw.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/liblistensoundmodel2.so:system/vendor/lib/liblistensoundmodel2.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libllvd_smore.so:system/vendor/lib/libllvd_smore.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libllvd_sw_tnr.so:system/vendor/lib/libllvd_sw_tnr.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libllvm-glnext.so:system/vendor/lib/libllvm-glnext.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/liblocationservice.so:system/vendor/lib/liblocationservice.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/liblocationservice_glue.so:system/vendor/lib/liblocationservice_glue.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/liblowi_client.so:system/vendor/lib/liblowi_client.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/liblowi_wifihal.so:system/vendor/lib/liblowi_wifihal.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/liblowi_wifihal_nl.so:system/vendor/lib/liblowi_wifihal_nl.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmdsprpc.so:system/vendor/lib/libmdsprpc.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmm-als.so:system/vendor/lib/libmm-als.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmm-disp-apis.so:system/vendor/lib/libmm-disp-apis.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmm-dspp-utils.so:system/vendor/lib/libmm-dspp-utils.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmm-hdcpmgr.so:system/vendor/lib/libmm-hdcpmgr.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmm-qdcm-diag.so:system/vendor/lib/libmm-qdcm-diag.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmm-qdcm.so:system/vendor/lib/libmm-qdcm.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmQSM.so:system/vendor/lib/libmmQSM.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera2_dcrf.so:system/vendor/lib/libmmcamera2_dcrf.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera2_frame_algorithm.so:system/vendor/lib/libmmcamera2_frame_algorithm.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera2_mct.so:system/vendor/lib/libmmcamera2_mct.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera2_pp_buf_mgr.so:system/vendor/lib/libmmcamera2_pp_buf_mgr.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera2_sensor_debug.so:system/vendor/lib/libmmcamera2_sensor_debug.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_cac3_lib.so:system/vendor/lib/libmmcamera_cac3_lib.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_chromaflash_lib.so:system/vendor/lib/libmmcamera_chromaflash_lib.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_csidtg.so:system/vendor/lib/libmmcamera_csidtg.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_dbg.so:system/vendor/lib/libmmcamera_dbg.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_dcrf_lib.so:system/vendor/lib/libmmcamera_dcrf_lib.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_dummyalgo.so:system/vendor/lib/libmmcamera_dummyalgo.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_dw9761b_eeprom.so:system/vendor/lib/libmmcamera_dw9761b_eeprom.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_dw9807_eeprom.so:system/vendor/lib/libmmcamera_dw9807_eeprom.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_eebinparse.so:system/vendor/lib/libmmcamera_eebinparse.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_eeprom_util.so:system/vendor/lib/libmmcamera_eeprom_util.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_eztune_module.so:system/vendor/lib/libmmcamera_eztune_module.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_imglib_faceproc_adspstub.so:system/vendor/lib/libmmcamera_imglib_faceproc_adspstub.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_imx214.so:system/vendor/lib/libmmcamera_imx214.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_imx219.so:system/vendor/lib/libmmcamera_imx219.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_imx230.so:system/vendor/lib/libmmcamera_imx230.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_imx241.so:system/vendor/lib/libmmcamera_imx241.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_imx258.so:system/vendor/lib/libmmcamera_imx258.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_imx258_gt24c16_eeprom.so:system/vendor/lib/libmmcamera_imx258_gt24c16_eeprom.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_imx298.so:system/vendor/lib/libmmcamera_imx298.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_isp_abf40.so:system/vendor/lib/libmmcamera_isp_abf40.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_isp_bcc40.so:system/vendor/lib/libmmcamera_isp_bcc40.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_isp_be_stats44.so:system/vendor/lib/libmmcamera_isp_be_stats44.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_isp_bf_stats47.so:system/vendor/lib/libmmcamera_isp_bf_stats47.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_isp_bg_stats44.so:system/vendor/lib/libmmcamera_isp_bg_stats44.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_isp_bhist_stats44.so:system/vendor/lib/libmmcamera_isp_bhist_stats44.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_isp_bpc40.so:system/vendor/lib/libmmcamera_isp_bpc40.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_isp_chroma_enhan40.so:system/vendor/lib/libmmcamera_isp_chroma_enhan40.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_isp_chroma_suppress40.so:system/vendor/lib/libmmcamera_isp_chroma_suppress40.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_isp_clamp_encoder40.so:system/vendor/lib/libmmcamera_isp_clamp_encoder40.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_isp_clamp_video40.so:system/vendor/lib/libmmcamera_isp_clamp_video40.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_isp_clamp_viewfinder40.so:system/vendor/lib/libmmcamera_isp_clamp_viewfinder40.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_isp_color_correct40.so:system/vendor/lib/libmmcamera_isp_color_correct40.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_isp_color_xform_encoder40.so:system/vendor/lib/libmmcamera_isp_color_xform_encoder40.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_isp_color_xform_viewfinder40.so:system/vendor/lib/libmmcamera_isp_color_xform_viewfinder40.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_isp_cs_stats44.so:system/vendor/lib/libmmcamera_isp_cs_stats44.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_isp_demosaic40.so:system/vendor/lib/libmmcamera_isp_demosaic40.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_isp_demux40.so:system/vendor/lib/libmmcamera_isp_demux40.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_isp_fovcrop_encoder40.so:system/vendor/lib/libmmcamera_isp_fovcrop_encoder40.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_isp_fovcrop_viewfinder40.so:system/vendor/lib/libmmcamera_isp_fovcrop_viewfinder40.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_isp_gamma40.so:system/vendor/lib/libmmcamera_isp_gamma40.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_isp_ihist_stats44.so:system/vendor/lib/libmmcamera_isp_ihist_stats44.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_isp_linearization40.so:system/vendor/lib/libmmcamera_isp_linearization40.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_isp_ltm44.so:system/vendor/lib/libmmcamera_isp_ltm44.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_isp_luma_adaptation40.so:system/vendor/lib/libmmcamera_isp_luma_adaptation40.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_isp_mce40.so:system/vendor/lib/libmmcamera_isp_mce40.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_isp_mesh_rolloff40.so:system/vendor/lib/libmmcamera_isp_mesh_rolloff40.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_isp_rs_stats44.so:system/vendor/lib/libmmcamera_isp_rs_stats44.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_isp_scaler_encoder44.so:system/vendor/lib/libmmcamera_isp_scaler_encoder44.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_isp_scaler_viewfinder44.so:system/vendor/lib/libmmcamera_isp_scaler_viewfinder44.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_isp_sce40.so:system/vendor/lib/libmmcamera_isp_sce40.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_isp_sub_module.so:system/vendor/lib/libmmcamera_isp_sub_module.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_isp_template.so:system/vendor/lib/libmmcamera_isp_template.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_isp_wb40.so:system/vendor/lib/libmmcamera_isp_wb40.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_le2464c_master_eeprom.so:system/vendor/lib/libmmcamera_le2464c_master_eeprom.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_llvd.so:system/vendor/lib/libmmcamera_llvd.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_m24c64s_eeprom.so:system/vendor/lib/libmmcamera_m24c64s_eeprom.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_onsemi_cat24c16_eeprom.so:system/vendor/lib/libmmcamera_onsemi_cat24c16_eeprom.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_onsemi_cat24c32_eeprom.so:system/vendor/lib/libmmcamera_onsemi_cat24c32_eeprom.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_onsemi_cat24c64_eeprom.so:system/vendor/lib/libmmcamera_onsemi_cat24c64_eeprom.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_optizoom_lib.so:system/vendor/lib/libmmcamera_optizoom_lib.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_ov13850.so:system/vendor/lib/libmmcamera_ov13850.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_ov13850_q13v06k.so:system/vendor/lib/libmmcamera_ov13850_q13v06k.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_ov2685.so:system/vendor/lib/libmmcamera_ov2685.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_ov2685_scv3b4035.so:system/vendor/lib/libmmcamera_ov2685_scv3b4035.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_ov4688.so:system/vendor/lib/libmmcamera_ov4688.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_ov4688_eeprom.so:system/vendor/lib/libmmcamera_ov4688_eeprom.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_ov5645.so:system/vendor/lib/libmmcamera_ov5645.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_ov5670.so:system/vendor/lib/libmmcamera_ov5670.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_ov8858.so:system/vendor/lib/libmmcamera_ov8858.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_ov8865.so:system/vendor/lib/libmmcamera_ov8865.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_ppbase_module.so:system/vendor/lib/libmmcamera_ppbase_module.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_s5k3l2xx.so:system/vendor/lib/libmmcamera_s5k3l2xx.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_s5k3m2xm.so:system/vendor/lib/libmmcamera_s5k3m2xm.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_s5k3m2xx.so:system/vendor/lib/libmmcamera_s5k3m2xx.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_s5k3p3sx.so:system/vendor/lib/libmmcamera_s5k3p3sx.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_s5k3p8sx.so:system/vendor/lib/libmmcamera_s5k3p8sx.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_s5k3p8sx_ak7372.so:system/vendor/lib/libmmcamera_s5k3p8sx_ak7372.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_s5k4h5yc.so:system/vendor/lib/libmmcamera_s5k4h5yc.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_s5k5e3yx.so:system/vendor/lib/libmmcamera_s5k5e3yx.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_s5k6b2yx.so:system/vendor/lib/libmmcamera_s5k6b2yx.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_sony_imx214_eeprom.so:system/vendor/lib/libmmcamera_sony_imx214_eeprom.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_sony_imx298_eeprom.so:system/vendor/lib/libmmcamera_sony_imx298_eeprom.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_sonyimx135_eeprom.so:system/vendor/lib/libmmcamera_sonyimx135_eeprom.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_sr259.so:system/vendor/lib/libmmcamera_sr259.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_sr846.so:system/vendor/lib/libmmcamera_sr846.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_stillmore_lib.so:system/vendor/lib/libmmcamera_stillmore_lib.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_sunny_8865_eeprom.so:system/vendor/lib/libmmcamera_sunny_8865_eeprom.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_sunny_q13v06k_eeprom.so:system/vendor/lib/libmmcamera_sunny_q13v06k_eeprom.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_sunny_q5v41b_eeprom.so:system/vendor/lib/libmmcamera_sunny_q5v41b_eeprom.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_sw_tnr.so:system/vendor/lib/libmmcamera_sw_tnr.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_thread_services.so:system/vendor/lib/libmmcamera_thread_services.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_trueportrait_lib.so:system/vendor/lib/libmmcamera_trueportrait_lib.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_tuning.so:system/vendor/lib/libmmcamera_tuning.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_tuning_lookup.so:system/vendor/lib/libmmcamera_tuning_lookup.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_ubifocus_lib.so:system/vendor/lib/libmmcamera_ubifocus_lib.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_vpu_module.so:system/vendor/lib/libmmcamera_vpu_module.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmcamera_zc535_eeprom.so:system/vendor/lib/libmmcamera_zc535_eeprom.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmhttpstack.so:system/vendor/lib/libmmhttpstack.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmiipstreammmihttp.so:system/vendor/lib/libmmiipstreammmihttp.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmipstreamaal.so:system/vendor/lib/libmmipstreamaal.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmipstreamnetwork.so:system/vendor/lib/libmmipstreamnetwork.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmipstreamsourcehttp.so:system/vendor/lib/libmmipstreamsourcehttp.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmipstreamutils.so:system/vendor/lib/libmmipstreamutils.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmparser.so:system/vendor/lib/libmmparser.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmparser_lite.so:system/vendor/lib/libmmparser_lite.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmqjpegdma.so:system/vendor/lib/libmmqjpegdma.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmrtpdecoder.so:system/vendor/lib/libmmrtpdecoder.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmrtpencoder.so:system/vendor/lib/libmmrtpencoder.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmsw_detail_enhancement.so:system/vendor/lib/libmmsw_detail_enhancement.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmsw_math.so:system/vendor/lib/libmmsw_math.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmsw_opencl.so:system/vendor/lib/libmmsw_opencl.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libmmsw_platform.so:system/vendor/lib/libmmsw_platform.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libnative_audio_latency_jni.so:system/vendor/lib/libnative_audio_latency_jni.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libois_lc898122.so:system/vendor/lib/libois_lc898122.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/liboptizoom.so:system/vendor/lib/liboptizoom.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libqc-opt.so:system/vendor/lib/libqc-opt.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libqcmaputils.so:system/vendor/lib/libqcmaputils.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libqct_resampler.so:system/vendor/lib/libqct_resampler.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libqisl.so:system/vendor/lib/libqisl.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libqomx_jpegdec.so:system/vendor/lib/libqomx_jpegdec.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libqomx_jpegenc_pipe.so:system/vendor/lib/libqomx_jpegenc_pipe.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libqti-at.so:system/vendor/lib/libqti-at.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libqti-gt.so:system/vendor/lib/libqti-gt.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libqti-iop-client.so:system/vendor/lib/libqti-iop-client.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libqti-perfd-client.so:system/vendor/lib/libqti-perfd-client.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libquipc_os_api.so:system/vendor/lib/libquipc_os_api.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libsc-a2xx.so:system/vendor/lib/libsc-a2xx.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libscalar.so:system/vendor/lib/libscalar.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libsd_sdk_display.so:system/vendor/lib/libsd_sdk_display.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libsdm-color.so:system/vendor/lib/libsdm-color.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libsdm-diag.so:system/vendor/lib/libsdm-diag.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libsdm-disp-apis.so:system/vendor/lib/libsdm-disp-apis.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libsdmextension.so:system/vendor/lib/libsdmextension.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libsecureui.so:system/vendor/lib/libsecureui.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libsecureui_svcsock.so:system/vendor/lib/libsecureui_svcsock.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libsecureuisvc_jni.so:system/vendor/lib/libsecureuisvc_jni.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libseemore.so:system/vendor/lib/libseemore.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libsensor_reg.so:system/vendor/lib/libsensor_reg.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libsubsystem_control.so:system/vendor/lib/libsubsystem_control.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libsurround_3mic_proc.so:system/vendor/lib/libsurround_3mic_proc.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libswvdec.so:system/vendor/lib/libswvdec.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libthermalioctl.so:system/vendor/lib/libthermalioctl.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libtm_interface.so:system/vendor/lib/libtm_interface.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libtrueportrait.so:system/vendor/lib/libtrueportrait.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libtzdrmgenprov.so:system/vendor/lib/libtzdrmgenprov.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libubifocus.so:system/vendor/lib/libubifocus.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libulp2.so:system/vendor/lib/libulp2.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libvoice-svc.so:system/vendor/lib/libvoice-svc.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libvqzip.so:system/vendor/lib/libvqzip.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libwfdrtsp.so:system/vendor/lib/libwfdrtsp.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libwms.so:system/vendor/lib/libwms.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libxt_native.so:system/vendor/lib/libxt_native.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libxtadapter.so:system/vendor/lib/libxtadapter.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/libxtwifi_ulp_adaptor.so:system/vendor/lib/libxtwifi_ulp_adaptor.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/sensor_calibrate.so:system/vendor/lib/sensor_calibrate.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/sensors.ssc.so:system/vendor/lib/sensors.ssc.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/test_suite_all_modules.so:system/vendor/lib/test_suite_all_modules.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/test_suite_no_sensor.so:system/vendor/lib/test_suite_no_sensor.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/test_suite_pproc.so:system/vendor/lib/test_suite_pproc.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/test_suite_vfe.so:system/vendor/lib/test_suite_vfe.so

# Vendor EGL libs
PRODUCT_COPY_FILES += \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/egl/eglSubDriverAndroid.so:system/vendor/lib/egl/eglSubDriverAndroid.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/egl/libESXEGL_adreno.so:system/vendor/lib/egl/libESXEGL_adreno.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/egl/libESXGLESv1_CM_adreno.so:system/vendor/lib/egl/libESXGLESv1_CM_adreno.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/egl/libESXGLESv2_adreno.so:system/vendor/lib/egl/libESXGLESv2_adreno.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/egl/libQTapGLES.so:system/vendor/lib/egl/libQTapGLES.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/egl/libRBEGL_adreno.so:system/vendor/lib/egl/libRBEGL_adreno.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/egl/libRBGLESv1_CM_adreno.so:system/vendor/lib/egl/libRBGLESv1_CM_adreno.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/egl/libRBGLESv2_adreno.so:system/vendor/lib/egl/libRBGLESv2_adreno.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/egl/libq3dtools_esx.so:system/vendor/lib/egl/libq3dtools_esx.so

# Vendor HAL libs
PRODUCT_COPY_FILES += \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/hw/gatekeeper.msm8937.so:system/vendor/lib/hw/gatekeeper.msm8937.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/hw/keystore.msm8937.so:system/vendor/lib/hw/keystore.msm8937.so

# Vendor MediaDRM libs
PRODUCT_COPY_FILES += \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so

# Vendor SoundFX libs
PRODUCT_COPY_FILES += \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so \
    vendor/samsung/elitelte_kor/proprietary/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so

# Vendor binaries
PRODUCT_COPY_FILES += \
    vendor/samsung/elitelte_kor/proprietary/vendor/bin/audioflacapp:system/vendor/bin/audioflacapp \
    vendor/samsung/elitelte_kor/proprietary/vendor/bin/chamomile_provision:system/vendor/bin/chamomile_provision \
    vendor/samsung/elitelte_kor/proprietary/vendor/bin/mm-pp-daemon:system/vendor/bin/mm-pp-daemon \
    vendor/samsung/elitelte_kor/proprietary/vendor/bin/mm-pp-dpps:system/vendor/bin/mm-pp-dpps \
    vendor/samsung/elitelte_kor/proprietary/vendor/bin/mm-qjpeg-dec-test:system/vendor/bin/mm-qjpeg-dec-test \
    vendor/samsung/elitelte_kor/proprietary/vendor/bin/mm-qjpeg-enc-test:system/vendor/bin/mm-qjpeg-enc-test \
    vendor/samsung/elitelte_kor/proprietary/vendor/bin/mm-qomx-idec-test:system/vendor/bin/mm-qomx-idec-test \
    vendor/samsung/elitelte_kor/proprietary/vendor/bin/mm-qomx-ienc-test:system/vendor/bin/mm-qomx-ienc-test \
    vendor/samsung/elitelte_kor/proprietary/vendor/bin/perfd:system/vendor/bin/perfd \
    vendor/samsung/elitelte_kor/proprietary/vendor/bin/qjpeg-dma-test:system/vendor/bin/qjpeg-dma-test \
    vendor/samsung/elitelte_kor/proprietary/vendor/bin/qseeproxydaemon:system/vendor/bin/qseeproxydaemon \
    vendor/samsung/elitelte_kor/proprietary/vendor/bin/qseeproxysampledaemon:system/vendor/bin/qseeproxysampledaemon \
    vendor/samsung/elitelte_kor/proprietary/vendor/bin/thermal-engine:system/vendor/bin/thermal-engine

# Vendor etc configs
PRODUCT_COPY_FILES += \
    vendor/samsung/elitelte_kor/proprietary/vendor/etc/RIDL/qdss.cfg:system/vendor/etc/RIDL/qdss.cfg \
    vendor/samsung/elitelte_kor/proprietary/vendor/etc/audio_output_policy.conf:system/vendor/etc/audio_output_policy.conf \
    vendor/samsung/elitelte_kor/proprietary/vendor/etc/msm_irqbalance.conf:system/vendor/etc/msm_irqbalance.conf

# System HAL libs
PRODUCT_COPY_FILES += \
    vendor/samsung/elitelte_kor/proprietary/lib/hw/audio.a2dp.default.so:system/lib/hw/audio.a2dp.default.so \
    vendor/samsung/elitelte_kor/proprietary/lib/hw/audio.playback_record.default.so:system/lib/hw/audio.playback_record.default.so \
    vendor/samsung/elitelte_kor/proprietary/lib/hw/audio.primary.default.so:system/lib/hw/audio.primary.default.so \
    vendor/samsung/elitelte_kor/proprietary/lib/hw/audio.primary.msm8937.so:system/lib/hw/audio.primary.msm8937.so \
    vendor/samsung/elitelte_kor/proprietary/lib/hw/audio.r_submix.default.so:system/lib/hw/audio.r_submix.default.so \
    vendor/samsung/elitelte_kor/proprietary/lib/hw/audio.tms.default.so:system/lib/hw/audio.tms.default.so \
    vendor/samsung/elitelte_kor/proprietary/lib/hw/audio.usb.default.so:system/lib/hw/audio.usb.default.so \
    vendor/samsung/elitelte_kor/proprietary/lib/hw/audio_policy.default.so:system/lib/hw/audio_policy.default.so \
    vendor/samsung/elitelte_kor/proprietary/lib/hw/bluetooth.default.so:system/lib/hw/bluetooth.default.so \
    vendor/samsung/elitelte_kor/proprietary/lib/hw/camera.msm8937.so:system/lib/hw/camera.msm8937.so \
    vendor/samsung/elitelte_kor/proprietary/lib/hw/copybit.msm8937.so:system/lib/hw/copybit.msm8937.so \
    vendor/samsung/elitelte_kor/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/samsung/elitelte_kor/proprietary/lib/hw/gralloc.default.so:system/lib/hw/gralloc.default.so \
    vendor/samsung/elitelte_kor/proprietary/lib/hw/gralloc.msm8937.so:system/lib/hw/gralloc.msm8937.so \
    vendor/samsung/elitelte_kor/proprietary/lib/hw/hwcomposer.msm8937.so:system/lib/hw/hwcomposer.msm8937.so \
    vendor/samsung/elitelte_kor/proprietary/lib/hw/keystore.default.so:system/lib/hw/keystore.default.so \
    vendor/samsung/elitelte_kor/proprietary/lib/hw/lights.msm8937.so:system/lib/hw/lights.msm8937.so \
    vendor/samsung/elitelte_kor/proprietary/lib/hw/local_time.default.so:system/lib/hw/local_time.default.so \
    vendor/samsung/elitelte_kor/proprietary/lib/hw/memtrack.msm8937.so:system/lib/hw/memtrack.msm8937.so \
    vendor/samsung/elitelte_kor/proprietary/lib/hw/power.default.so:system/lib/hw/power.default.so \
    vendor/samsung/elitelte_kor/proprietary/lib/hw/power.qcom.so:system/lib/hw/power.qcom.so \
    vendor/samsung/elitelte_kor/proprietary/lib/hw/sensors.msm8937.so:system/lib/hw/sensors.msm8937.so \
    vendor/samsung/elitelte_kor/proprietary/lib/hw/vibrator.default.so:system/lib/hw/vibrator.default.so

# System EGL
PRODUCT_COPY_FILES += \
    vendor/samsung/elitelte_kor/proprietary/lib/egl/egl.cfg:system/lib/egl/egl.cfg \
    vendor/samsung/elitelte_kor/proprietary/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so

# Key system libs (RIL, etc)
PRODUCT_COPY_FILES += \
    vendor/samsung/elitelte_kor/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/elitelte_kor/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/elitelte_kor/proprietary/lib/librilutils.so:system/lib/librilutils.so \
    vendor/samsung/elitelte_kor/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so

# System binaries
PRODUCT_COPY_FILES += \
    vendor/samsung/elitelte_kor/proprietary/bin/adsprpcd:system/bin/adsprpcd \
    vendor/samsung/elitelte_kor/proprietary/bin/cnss-daemon:system/bin/cnss-daemon \
    vendor/samsung/elitelte_kor/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/samsung/elitelte_kor/proprietary/bin/mm-qcamera-app:system/bin/mm-qcamera-app \
    vendor/samsung/elitelte_kor/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/samsung/elitelte_kor/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/elitelte_kor/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
    vendor/samsung/elitelte_kor/proprietary/bin/wcnss_service:system/bin/wcnss_service

# System etc configs
PRODUCT_COPY_FILES += \
    vendor/samsung/elitelte_kor/proprietary/etc/Bluetooth_cal.acdb:system/etc/Bluetooth_cal.acdb \
    vendor/samsung/elitelte_kor/proprietary/etc/General_cal.acdb:system/etc/General_cal.acdb \
    vendor/samsung/elitelte_kor/proprietary/etc/Global_cal.acdb:system/etc/Global_cal.acdb \
    vendor/samsung/elitelte_kor/proprietary/etc/Handset_cal.acdb:system/etc/Handset_cal.acdb \
    vendor/samsung/elitelte_kor/proprietary/etc/Hdmi_cal.acdb:system/etc/Hdmi_cal.acdb \
    vendor/samsung/elitelte_kor/proprietary/etc/Headset_cal.acdb:system/etc/Headset_cal.acdb \
    vendor/samsung/elitelte_kor/proprietary/etc/Speaker_cal.acdb:system/etc/Speaker_cal.acdb \
    vendor/samsung/elitelte_kor/proprietary/etc/audio_effects.conf:system/etc/audio_effects.conf \
    vendor/samsung/elitelte_kor/proprietary/etc/audio_effects_sec.conf:system/etc/audio_effects_sec.conf \
    vendor/samsung/elitelte_kor/proprietary/etc/audio_platform_info.xml:system/etc/audio_platform_info.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/audio_platform_info_extcodec.xml:system/etc/audio_platform_info_extcodec.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/audio_policy.conf:system/etc/audio_policy.conf \
    vendor/samsung/elitelte_kor/proprietary/etc/flp.conf:system/etc/flp.conf \
    vendor/samsung/elitelte_kor/proprietary/etc/gps.conf:system/etc/gps.conf \
    vendor/samsung/elitelte_kor/proprietary/etc/izat.conf:system/etc/izat.conf \
    vendor/samsung/elitelte_kor/proprietary/etc/lowi.conf:system/etc/lowi.conf \
    vendor/samsung/elitelte_kor/proprietary/etc/media_codecs.xml:system/etc/media_codecs.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/media_codecs_8956.xml:system/etc/media_codecs_8956.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/media_codecs_google_audio.xml:system/etc/media_codecs_google_audio.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/media_codecs_google_telephony.xml:system/etc/media_codecs_google_telephony.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/media_codecs_google_video.xml:system/etc/media_codecs_google_video.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/media_codecs_performance.xml:system/etc/media_codecs_performance.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/media_codecs_sec_primary.xml:system/etc/media_codecs_sec_primary.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/media_codecs_sec_secondary.xml:system/etc/media_codecs_sec_secondary.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/media_profiles.xml:system/etc/media_profiles.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/media_profiles_8956.xml:system/etc/media_profiles_8956.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/mixer_paths.xml:system/etc/mixer_paths.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/mixer_paths_mtp.xml:system/etc/mixer_paths_mtp.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/mixer_paths_qrd_sku1.xml:system/etc/mixer_paths_qrd_sku1.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/mixer_paths_qrd_sku2.xml:system/etc/mixer_paths_qrd_sku2.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/mixer_paths_qrd_skuh.xml:system/etc/mixer_paths_qrd_skuh.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/mixer_paths_qrd_skuhf.xml:system/etc/mixer_paths_qrd_skuhf.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/mixer_paths_qrd_skui.xml:system/etc/mixer_paths_qrd_skui.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/mixer_paths_qrd_skum.xml:system/etc/mixer_paths_qrd_skum.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/mixer_paths_qrd_skun.xml:system/etc/mixer_paths_qrd_skun.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/mixer_paths_skuk.xml:system/etc/mixer_paths_skuk.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/mixer_paths_wcd9306.xml:system/etc/mixer_paths_wcd9306.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/mixer_paths_wcd9326.xml:system/etc/mixer_paths_wcd9326.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/mixer_paths_wcd9330.xml:system/etc/mixer_paths_wcd9330.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/mixer_paths_wcd9335.xml:system/etc/mixer_paths_wcd9335.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/sound_trigger_mixer_paths.xml:system/etc/sound_trigger_mixer_paths.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/sound_trigger_mixer_paths_wcd9306.xml:system/etc/sound_trigger_mixer_paths_wcd9306.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/sound_trigger_mixer_paths_wcd9330.xml:system/etc/sound_trigger_mixer_paths_wcd9330.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/sound_trigger_mixer_paths_wcd9335.xml:system/etc/sound_trigger_mixer_paths_wcd9335.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/sound_trigger_platform_info.xml:system/etc/sound_trigger_platform_info.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/thermal-engine.conf:system/etc/thermal-engine.conf

# Firmware files
PRODUCT_COPY_FILES += \
    vendor/samsung/elitelte_kor/proprietary/etc/firmware/DE.o.msm8937:system/etc/firmware/DE.o.msm8937 \
    vendor/samsung/elitelte_kor/proprietary/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
    vendor/samsung/elitelte_kor/proprietary/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
    vendor/samsung/elitelte_kor/proprietary/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
    vendor/samsung/elitelte_kor/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    vendor/samsung/elitelte_kor/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    vendor/samsung/elitelte_kor/proprietary/etc/firmware/a330_pfp.fw:system/etc/firmware/a330_pfp.fw \
    vendor/samsung/elitelte_kor/proprietary/etc/firmware/a330_pm4.fw:system/etc/firmware/a330_pm4.fw \
    vendor/samsung/elitelte_kor/proprietary/etc/firmware/a420_pfp.fw:system/etc/firmware/a420_pfp.fw \
    vendor/samsung/elitelte_kor/proprietary/etc/firmware/a420_pm4.fw:system/etc/firmware/a420_pm4.fw \
    vendor/samsung/elitelte_kor/proprietary/etc/firmware/a530_gpmu.fw2:system/etc/firmware/a530_gpmu.fw2 \
    vendor/samsung/elitelte_kor/proprietary/etc/firmware/a530_pfp.fw:system/etc/firmware/a530_pfp.fw \
    vendor/samsung/elitelte_kor/proprietary/etc/firmware/a530_pm4.fw:system/etc/firmware/a530_pm4.fw \
    vendor/samsung/elitelte_kor/proprietary/etc/firmware/a530v1_pfp.fw:system/etc/firmware/a530v1_pfp.fw \
    vendor/samsung/elitelte_kor/proprietary/etc/firmware/a530v1_pm4.fw:system/etc/firmware/a530v1_pm4.fw \
    vendor/samsung/elitelte_kor/proprietary/etc/firmware/a530v2_seq.fw2:system/etc/firmware/a530v2_seq.fw2 \
    vendor/samsung/elitelte_kor/proprietary/etc/firmware/a530v3_gpmu.fw2:system/etc/firmware/a530v3_gpmu.fw2 \
    vendor/samsung/elitelte_kor/proprietary/etc/firmware/a530v3_seq.fw2:system/etc/firmware/a530v3_seq.fw2 \
    vendor/samsung/elitelte_kor/proprietary/etc/firmware/cpp_firmware_v1_10_0.fw:system/etc/firmware/cpp_firmware_v1_10_0.fw \
    vendor/samsung/elitelte_kor/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
    vendor/samsung/elitelte_kor/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
    vendor/samsung/elitelte_kor/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    vendor/samsung/elitelte_kor/proprietary/etc/firmware/cpp_firmware_v1_4_0.fw:system/etc/firmware/cpp_firmware_v1_4_0.fw \
    vendor/samsung/elitelte_kor/proprietary/etc/firmware/cpp_firmware_v1_5_0.fw:system/etc/firmware/cpp_firmware_v1_5_0.fw \
    vendor/samsung/elitelte_kor/proprietary/etc/firmware/cpp_firmware_v1_5_2.fw:system/etc/firmware/cpp_firmware_v1_5_2.fw \
    vendor/samsung/elitelte_kor/proprietary/etc/firmware/cpp_firmware_v1_6_0.fw:system/etc/firmware/cpp_firmware_v1_6_0.fw \
    vendor/samsung/elitelte_kor/proprietary/etc/firmware/cpp_firmware_v1_8_0.fw:system/etc/firmware/cpp_firmware_v1_8_0.fw \
    vendor/samsung/elitelte_kor/proprietary/etc/firmware/ice40.bin:system/etc/firmware/ice40.bin \
    vendor/samsung/elitelte_kor/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    vendor/samsung/elitelte_kor/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    vendor/samsung/elitelte_kor/proprietary/etc/firmware/wlan/prima/WCNSS_cfg.dat:system/etc/firmware/wlan/prima/WCNSS_cfg.dat \
    vendor/samsung/elitelte_kor/proprietary/etc/firmware/wlan/prima/WCNSS_qcom_cfg.ini:system/etc/firmware/wlan/prima/WCNSS_qcom_cfg.ini \
    vendor/samsung/elitelte_kor/proprietary/etc/firmware/wlan/prima/WCNSS_qcom_wlan_nv.bin:system/etc/firmware/wlan/prima/WCNSS_qcom_wlan_nv.bin \
    vendor/samsung/elitelte_kor/proprietary/etc/firmware/wlan/prima/grippower.info:system/etc/firmware/wlan/prima/grippower.info

# WiFi configs
PRODUCT_COPY_FILES += \
    vendor/samsung/elitelte_kor/proprietary/etc/wifi/cred.conf:system/etc/wifi/cred.conf \
    vendor/samsung/elitelte_kor/proprietary/etc/wifi/fstman.ini:system/etc/wifi/fstman.ini \
    vendor/samsung/elitelte_kor/proprietary/etc/wifi/olsrd.conf:system/etc/wifi/olsrd.conf \
    vendor/samsung/elitelte_kor/proprietary/etc/wifi/p2p_supplicant_overlay.conf:system/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/samsung/elitelte_kor/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
    vendor/samsung/elitelte_kor/proprietary/etc/wifi/wpa_supplicant_overlay.conf:system/etc/wifi/wpa_supplicant_overlay.conf

# Bluetooth configs
PRODUCT_COPY_FILES += \
    vendor/samsung/elitelte_kor/proprietary/etc/bluetooth/auto_pair_devlist.conf:system/etc/bluetooth/auto_pair_devlist.conf \
    vendor/samsung/elitelte_kor/proprietary/etc/bluetooth/av_performance.conf:system/etc/bluetooth/av_performance.conf \
    vendor/samsung/elitelte_kor/proprietary/etc/bluetooth/bt_did.conf:system/etc/bluetooth/bt_did.conf \
    vendor/samsung/elitelte_kor/proprietary/etc/bluetooth/bt_stack.conf:system/etc/bluetooth/bt_stack.conf \
    vendor/samsung/elitelte_kor/proprietary/etc/bluetooth/iop_bt.db:system/etc/bluetooth/iop_bt.db \
    vendor/samsung/elitelte_kor/proprietary/etc/bluetooth/iop_device_list.conf:system/etc/bluetooth/iop_device_list.conf

# Sensor configs
PRODUCT_COPY_FILES += \
    vendor/samsung/elitelte_kor/proprietary/etc/sensors/hals.conf:system/etc/sensors/hals.conf \
    vendor/samsung/elitelte_kor/proprietary/etc/sensors/sensor_def_qcomdev.conf:system/etc/sensors/sensor_def_qcomdev.conf

# Camera configs
PRODUCT_COPY_FILES += \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/D05QL_s5k5e3yx_module_info.xml:system/etc/camera/D05QL_s5k5e3yx_module_info.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/L16OL_s5k3p3sx_module_info.xml:system/etc/camera/L16OL_s5k3p3sx_module_info.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/M05QS_imx241_module_info.xml:system/etc/camera/M05QS_imx241_module_info.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/M16QL_s5k3p8sx_ak7372_module_info.xml:system/etc/camera/M16QL_s5k3p8sx_ak7372_module_info.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/M16QL_s5k3p8sx_chromatix.xml:system/etc/camera/M16QL_s5k3p8sx_chromatix.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/O16QL_s5k3p8sx_chromatix.xml:system/etc/camera/O16QL_s5k3p8sx_chromatix.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/O16QL_s5k3p8sx_module_info.xml:system/etc/camera/O16QL_s5k3p8sx_module_info.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/P08QL_s5k4h5yc_module_info.xml:system/etc/camera/P08QL_s5k4h5yc_module_info.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/Q08QL_s5k4h5yc_module_info.xml:system/etc/camera/Q08QL_s5k4h5yc_module_info.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/R08QS_imx219_module_info.xml:system/etc/camera/R08QS_imx219_module_info.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/W13QS_imx258_module_info.xml:system/etc/camera/W13QS_imx258_module_info.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/Y08QF_sr846_chromatix.xml:system/etc/camera/Y08QF_sr846_chromatix.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/Y08QF_sr846_module_info.xml:system/etc/camera/Y08QF_sr846_module_info.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/imx214_chromatix.xml:system/etc/camera/imx214_chromatix.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/imx219_chromatix.xml:system/etc/camera/imx219_chromatix.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/imx219_elite_chromatix.xml:system/etc/camera/imx219_elite_chromatix.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/imx230_chromatix.xml:system/etc/camera/imx230_chromatix.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/imx241_chromatix.xml:system/etc/camera/imx241_chromatix.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/imx258_chromatix.xml:system/etc/camera/imx258_chromatix.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/msm8937_camera.xml:system/etc/camera/msm8937_camera.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/msm8937_camera_elitelte.xml:system/etc/camera/msm8937_camera_elitelte.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/msm8952_camera.xml:system/etc/camera/msm8952_camera.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/msm8996_camera.xml:system/etc/camera/msm8996_camera.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/ov13850_chromatix.xml:system/etc/camera/ov13850_chromatix.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/ov13850_q13v06k_chromatix.xml:system/etc/camera/ov13850_q13v06k_chromatix.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/ov4688_chromatix.xml:system/etc/camera/ov4688_chromatix.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/ov5670_chromatix.xml:system/etc/camera/ov5670_chromatix.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/ov8858_chromatix.xml:system/etc/camera/ov8858_chromatix.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/ov8865_chromatix.xml:system/etc/camera/ov8865_chromatix.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/s5k3l2xx_chromatix.xml:system/etc/camera/s5k3l2xx_chromatix.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/s5k3m2xm_chromatix.xml:system/etc/camera/s5k3m2xm_chromatix.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/s5k3m2xx_chromatix.xml:system/etc/camera/s5k3m2xx_chromatix.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/s5k3p3sx_chromatix.xml:system/etc/camera/s5k3p3sx_chromatix.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/s5k3p3sx_i16ql_chromatix.xml:system/etc/camera/s5k3p3sx_i16ql_chromatix.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/s5k4h5yc_chromatix.xml:system/etc/camera/s5k4h5yc_chromatix.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/s5k4h5yc_dw9807_chromatix.xml:system/etc/camera/s5k4h5yc_dw9807_chromatix.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/s5k5e3yx_chromatix.xml:system/etc/camera/s5k5e3yx_chromatix.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/s5k5e3yx_f2_2_chromatix.xml:system/etc/camera/s5k5e3yx_f2_2_chromatix.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/s5k6b2yx_chromatix.xml:system/etc/camera/s5k6b2yx_chromatix.xml \
    vendor/samsung/elitelte_kor/proprietary/etc/camera/sr259_chromatix.xml:system/etc/camera/sr259_chromatix.xml
